// export const USER_SERVICE_API = 'http://localhost:9001/api/v1'
// export const CORE_SERVICE_API = 'http://localhost:9002/api/v1'
// export const SOCKET_SERVICE_API = 'http://localhost:9003'
// export const NOTIFICATION_SERVICE_API = 'http://localhost:9004'
export const USER_SERVICE_API = 'https://user.rougeone.dev/api/v1'
export const CORE_SERVICE_API = 'https://core.rougeone.dev/api/v1'
export const SOCKET_SERVICE_API = 'https://socket.rougeone.dev'
export const NOTIFICATION_SERVICE_API = 'https://notification.rougeone.dev'
